### PR TITLE
fix: do not create a fake remote span if it does not exists

### PR DESCRIPTION
**Pull request by ttys3**
do not create a fake remote span if it does not exists, avoid `<root span not yet received>` when no remote span

remove the useless `trace_id` meta field, it has nothing to do with the final trace ID (at least it has no meaning in otlp, for jaeger, I do not know).

related issue:

https://github.com/davidB/axum-tracing-opentelemetry/issues/52#issuecomment-1484166015

### CODE REVIEW

**Comment by davidB** [comment]
It's nearly the orginal code (version 0.1). The issue with this approach it that "root span" as no trace_id
- not visible in log
- and (iirc) not visible if no child span is created

It's why I instroduce the "hack" of `create_context_with_trace` has mention in it's comment.

**Comment by ttys3** [comment]
the problem is, the hack casued this middleware's behavior diffs from any other (maybe wideused, I thought) middleware implementions.

for example  the behavior with the Golang echo framework middleware implementation: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/github.com/labstack/echo/otelecho/echo.go

and also the Rust actix framework middleware implementation: 
https://github.com/OutThereLabs/actix-web-opentelemetry/blob/main/src/middleware/trace.rs

both will not show `<root span not yet received>`  if the client request does not have text propagation headers.

**Comment by ttys3** [comment]
"not visible in log"
"and (iirc) not visible if no child span is created", 

each one, can you give a reproduce example ?

**Comment by davidB** [comment]
The test is missing actually.
iirc, to reproduce launch the example, call the enpoint with otlp (see README). You'll notice that trace_id is not set in the reaction of the span. It's also visible into your PR. the call to `info_span` doesn't have trace_id, because the opentelemetry span & trace are created after `info_span`.

**Comment by davidB** [comment]
I looked at the actixweb code you shared. The actixweb code is opentelemetry only it doesn't integrate the tracing part. And it's where I have the problem.

- with the original code (like you PR), opentelemetry span (and trace) is created after the tracing span, and so no trace_id in some log, events,...
- with the second try, I created a full opentelemetry span & trace first, then attach to the tracing span. In this case on OpenTelemetry we have 2 span (with a fake parent), because the attachment create an opentelemetry span iirc
- current implementation creates an opentelemetry trace & spancontext but with an invalid (000...) spanId, in this case no fake opentelemetry span send to collector, but the issue you mention.

(Maybe I wrongly remember the cases and symptoms)

**Comment by davidB** [comment]
On master (not yet releasd) I pushed an other way to fix this issue, if you want to take a look.
I would to add a dedicated test before release, but If it's too long I'll release without.

**Review by davidB — COMMENTED** [review]
see my previous comments.

I don't understand why the CI doesn't on your PR

**Comment by ttys3** [comment]
> On master (not yet releasd) I pushed an other way to fix this issue, if you want to take a look. I would to add a dedicated test before release, but If it's too long I'll release without.

just tested the latest main branch. it works.

image

**Comment by davidB** [comment]
Thanks for the feedback.

**Comment by davidB** [comment]
With 0.12, I removed the hack to have `trace_id` before tracing' span creation in every case. Because it's incompatible with how `tracing-opentelemetry` behaves.
I'm very sad about this removal, and I'll try to find an other way.
So it should fix the issue with this "phatom" span

**Comment by davidB** [comment]
Thanks for the bug & PR.
Give me your feedback about 0.12+

**Pull request closed without merging**
